### ISSUE TITLE
Broken Links: images not found

### ISSUE THREAD

**Issue by lex111** [dashvlas/awesome-ios-interview#1]

**Comment by dashvlas** [comment]
Thanx for pointing out. It's all fixed now, enjoy😊

**Comment by lex111** [comment]
Unfortunately, one image still does not appear :(
![image](https://user-images.githubusercontent.com/4408379/30722066-b3e87c2c-9f37-11e7-8ed3-a0b9e1291e35.png)

**Comment by dashvlas** [comment]
I have no idea, it's showed in my browser
![screen shot 2017-09-22 at 01 47 41](https://user-images.githubusercontent.com/20304226/30722157-3ffdb704-9f38-11e7-8bc9-75dc76ed3ba7.png)

**Comment by lex111** [comment]
Hehe, it turned out that my ad blocker blocked this image, sorry about that :smile: 
Apparently it did not like the name of the image "Banner.png", it probably took it for an advertising banner.
Thanks anyway, I added in whitelist to github.com in settings ad blocker.

**Comment by dashvlas** [comment]
Haha, thanks a lot, I'll change image name just in case :)
